# Generated by Django 4.2.5 on 2023-09-27 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visionApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_user',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default='2023-09-27 00:00:00'),
            preserve_default=False,
        ),
    ]
