# Generated by Django 4.2.5 on 2023-10-16 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visionApp', '0002_message_is_user_message_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personality', models.TextField()),
            ],
        ),
    ]
