# Generated by Django 4.2.5 on 2023-11-05 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visionApp', '0004_character_conversation_message_conversation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
