# Generated by Django 4.2.5 on 2023-11-13 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visionApp', '0005_alter_character_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='example_dialogues',
            new_name='examples',
        ),
        migrations.AddField(
            model_name='character',
            name='details',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
