# Generated by Django 4.2.5 on 2023-11-14 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visionApp', '0006_rename_example_dialogues_character_examples_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='name',
            new_name='character_name',
        ),
    ]
